### ISSUE TITLE
Problem with hybpiper check_dependencies 2.0.1

### ISSUE THREAD

**Issue by antonambroa** [mossmatters/HybPiper#102]
Hi,

I have an error when the command `hybpiper check_dependencies` runs. I have installed following the instructions through conda and an installation in another environment from source with all the dependencies correctly installed. This is the output:

```
Traceback (most recent call last):
  File "/opt/cesga/2020/software/Compiler/gcccore/system/hybpiper/2.0.1/bin/hybpiper", line 11, in <module>
    load_entry_point('hybpiper==2.0', 'console_scripts', 'hybpiper')()
  File "/opt/cesga/2020/software/Compiler/gcccore/system/hybpiper/2.0.1/lib/python3.7/site-packages/hybpiper-2.0-py3.7.egg/hybpiper/assemble.py", line 1708, in main
AttributeError: 'Namespace' object has no attribute 'run_profiler'

```
The rest of the program seems to run OK.

**Comment by chrisjackson-pellicle** [comment]
Hi @antonambroa,

Thanks for reporting that - an oversight on my behalf! I've fixed it in now (and updated the Mac and Linux conda packages).

Cheers,

Chris
