### ISSUE TITLE
Spades assembly failes on test-dataset and real dataset

### ISSUE THREAD

**Issue by ClaudiaPaetzold** [mossmatters/HybPiper#109]
I have installed HybPiper in a conda environment following the steps in the Installation instructions. However, when I run the test-dataset assembly, it failes, as no \*_spades   directories are found within the sample/gene directories. Is there a problem with the assembly command? Or have I done something wrong:

Im running on Debian GNU/Linux 11 (bullseye) with conda 22.11.1

All prior steps (mapping and sorting reads into directories) work without problem and both sample directories contain subdirectories for the different genes, each of which containes the geneXXX_interleafed.fasta file. When I run the spades command given in the "spades_initial_commands.txt" file directly, it works and produces a complete assembly. So there seems to be some kind of hang-up when running the spades-assembly command from within the hybpiper-assemble script. 

```
                                                 T
                                                        T
                                         C  G
 _    _            _       _____      T        G        A
| |  | |          | |     |  _  \  A              A  A
| |__| | __    __ | |___  | |_| |  _   _____   _____   _____
|  __  | \ \  / / |  _  \ |  ___/ | | |  _  \ |  _  | |  _  \
| |  | |  \ \/ /  | |_| | | |     | | | |_| | |  __/  | |  --
|_|  |_|   \  /   |_____/ |_|     |_| |  ___/ |_____| |_|
           / /                        | |
          /_/                         |_|

[INFO]:    HybPiper was called with these arguments:
           /home/cpaetzold/miniconda3/envs/hybpiper/bin/hybpiper assemble -r
           NZ728_R1_test.fastq NZ728_R2_test.fastq -t_dna test_targets.fasta --prefix
           NZ728 --bwa --run_intronerate

[INFO]:    Number of cpus/threads not specified, using all available (36).
[INFO]:    Checking for external dependencies:

blastx               found at /home/cpaetzold/miniconda3/envs/hybpiper/bin/blastx
exonerate            found at /home/cpaetzold/miniconda3/envs/hybpiper/bin/exonerate
parallel             found at /home/cpaetzold/miniconda3/envs/hybpiper/bin/parallel
makeblastdb          found at /home/cpaetzold/miniconda3/envs/hybpiper/bin/makeblastdb
spades.py            found at /home/cpaetzold/miniconda3/envs/hybpiper/bin/spades.py
bwa                  found at /home/cpaetzold/miniconda3/envs/hybpiper/bin/bwa
samtools             found at /home/cpaetzold/miniconda3/envs/hybpiper/bin/samtools
bbmap.sh             found at /home/cpaetzold/miniconda3/envs/hybpiper/bin/bbmap.sh
bbmerge.sh           found at /home/cpaetzold/miniconda3/envs/hybpiper/bin/bbmerge.sh
diamond              found at /home/cpaetzold/miniconda3/envs/hybpiper/bin/diamond
mafft                found at /home/cpaetzold/miniconda3/envs/hybpiper/bin/mafft

[INFO]:    Everything looks good!
[INFO]:    Checking target file FASTA header formatting...
[INFO]:    The target file FASTA header formatting looks good!
[INFO]:    The target file contains at least one sequence for 13 unique genes.
[WARNING]: There are 1 sequences in your target file that contain unexpected stop codons
           when translated in the first forwards frame. If your target file contains only
           protein-coding sequences, please check these sequences, and/or run "hybpiper
           fix_targetfile". Sequence names can be found in the sample log file (if running
           "hybpiper assemble") or printed below (if running "hybpiper check_targetfile").

[WARNING]: There are 1 sequences in your target file that are not multiples of three. If
           your target file contains only protein-coding sequences, please check these
           sequences, and/or run "hybpiper fix_targetfile". Sequence names can be found in
           the sample log file (if running "hybpiper assemble") or printed below (if
           running "hybpiper check_targetfile").

[INFO]:    Making nucleotide bwa index in current directory.
[CMD]:     bwa index test_targets.fasta
[CMD]:     bwa mem -t 36 test_targets.fasta /home/cpaetzold/Software/HybPiper/
           test_dataset/NZ728_R1_test.fastq /home/cpaetzold/Software/HybPiper/
           test_dataset/NZ728_R2_test.fastq  | samtools view -h -b -S - >  NZ728.bam
[INFO]:    Gathering IDs for mapped reads...
[INFO]:    In total, 25900 reads from the paired-end read files will be distributed to gene directories
[NOTE]:    Distributing paired reads to gene directories
           Elapsed Time: 0:00:00|##################################################################################################################|Time:  0:00:00
[NOTE]:    0 genes had no good matches.
[NOTE]:    Running initial SPAdes assemblies for 13 genes with reads...
[INFO]:    See file "spades_initial_commands.txt" for a list of SPAdes commands
/bin/sh: 1: time: not found
[WARNING]: One or more genes had an error with SPAdes assembly. This may be due to low coverage.
[WARNING]: Total number of genes with failed initial SPAdes run: 13. Gene names can be found in the sample log file.
[INFO]:    Finished running initial SPAdes assemblies for all genes with reads!
[NOTE]:    Re-running SPAdes assemblies for 13 genes with unsuccessful initial assemblies...
Traceback (most recent call last):
  File "/home/cpaetzold/miniconda3/envs/hybpiper/bin/hybpiper", line 8, in <module>
    sys.exit(main())
  File "/home/cpaetzold/miniconda3/envs/hybpiper/lib/python3.9/site-packages/hybpiper/assemble.py", line 1775, in main
    args.func(args)
  File "/home/cpaetzold/miniconda3/envs/hybpiper/lib/python3.9/site-packages/hybpiper/assemble.py", line 1427, in assemble
    spades_genelist = spades(genes,
  File "/home/cpaetzold/miniconda3/envs/hybpiper/lib/python3.9/site-packages/hybpiper/assemble.py", line 807, in spades
    spades_duds = spades_runner.rerun_spades('failed_spades.txt', cov_cutoff=cov_cutoff, cpu=cpu)
  File "/home/cpaetzold/miniconda3/envs/hybpiper/lib/python3.9/site-packages/hybpiper/spades_runner.py", line 183, in rerun_spades
    all_kmers = [int(x[1:]) for x in os.listdir(os.path.join(gene, f'{gene}_spades')) if
FileNotFoundError: [Errno 2] No such file or directory: 'gene074/gene074_spades'

```

**Comment by chrisjackson-pellicle** [comment]
Hi @ClaudiaPaetzold,

This is happening because your Linux machine doesn't have the program `time` installed. In the screen output you posted above you can see the message `/bin/sh: 1: time: not found`. 

This is my fault! We realised a couple of months ago that `time` isn't always installed in all Linux distributions (see https://github.com/mossmatters/HybPiper/issues/89#issuecomment-1336813653), and I thought I'd removed it from HybPiper entirely. It turns out there's still a call to `time` when running the SPAdes assemblies via `parallel`: https://github.com/mossmatters/HybPiper/blob/274dcbe71333b6fffae19f48c78dc4a28079cc83/hybpiper/spades_runner.py#L117

As a temporary work-around, you could just install `time` via conda in your conda `hybpiper` environment (i.e., `conda install -c conda-forge time`, see [here](https://anaconda.org/conda-forge/time)). I'll be releasing an update to HybPiper later this week, so I'll permanently remove the call to `time` when running SPAdes for that, and it shouldn't be an issue for any future installs of HybPiper.

Let me know if there are any problems!

Cheers,

Chris

**Comment by ClaudiaPaetzold** [comment]
Dear @chrisjackson-pellicle,
thank you so much for your quick reply. I installed the time module and it works without a hitch now. Thank you.
