### ISSUE TITLE
Lower recovery rate using Hybpiper v.2.1.6 compared to v.1.3.1

### ISSUE THREAD

**Issue by bingli8899** [mossmatters/HybPiper#141]
Hello, 

I hope this message finds you well. I was running a project with 16 samples and 1815 genes in the target fasta file. When running Hybpiper v.2.1.6, I got a much lower recovery rate for mapped genes with longer than 25%, 50%, and 75% recovery (576, 551, and 512 out of 1816 genes respectively). When I re-did this using Hybpiper v.1.3.1, I got high recovery rates (1490, 1427, and 1276 out of 1816 genes respectively for 25%, 50% and 75% recovery rates). I attached my bash scripts and the test statistics to this email, and I am wondering how to solve this problem in Hybpiper version 2. Do I need to change any paramerers? 

[files_hybpiper_v1_v2.zip](https://github.com/mossmatters/HybPiper/files/14747470/files_hybpiper_v1_v2.zip)

**Comment by chrisjackson-pellicle** [comment]
Hi @bingli8899,

Looking at your stats files from your v1 and v2 runs - you can see that the numbers in the "GenesWithContigs" column are much the same between versions, but that the numbers in the "GenesWithSeqs" column (see [here](https://github.com/mossmatters/HybPiper/wiki/Tutorial#summary-statistics) for an explanation of these columnn) are much lower for v2. This makes me think something went wrong during the Exonerate step of your v2 runs. 

Can you upload the sample log for one of your samples, e.g `TGB02_L0002`, which will be in the sample directory and look like `<prefix>_hybpiper_assemble_<date_time>.log`? Also, if you've kept the standard out and standard error logs from the v2 runs, can you upload those as well?

Cheers,

Chris

**Comment by bingli8899** [comment]
Hi Chris, 

Thanks for your response and help! I attached the log files here. 

Best, 
[log.zip](https://github.com/mossmatters/HybPiper/files/14830333/log.zip)

Bing

**Comment by chrisjackson-pellicle** [comment]
Hi Bing - I don't think the log files you attached are the right ones. You can see they contain e.g.:

```
2024-03-21 16:55:36,518 - utils.py - hybpiper.assemble - log_or_print - INFO - blastx               not found in your $PATH!
2024-03-21 16:55:36,518 - utils.py - hybpiper.assemble - log_or_print - INFO - exonerate            not found in your $PATH!
2024-03-21 16:55:36,518 - utils.py - hybpiper.assemble - log_or_print - INFO - parallel             found at /usr/bin/parallel
2024-03-21 16:55:36,518 - utils.py - hybpiper.assemble - log_or_print - INFO - makeblastdb          not found in your $PATH!
2024-03-21 16:55:36,519 - utils.py - hybpiper.assemble - log_or_print - INFO - spades.py            not found in your $PATH!
2024-03-21 16:55:36,519 - utils.py - hybpiper.assemble - log_or_print - INFO - bwa                  found at /home/bli283/software/bwa/bwa
2024-03-21 16:55:36,519 - utils.py - hybpiper.assemble - log_or_print - INFO - samtools             found at /home/bli283/SamTools/samtools-1.15.1/samtools
2024-03-21 16:55:36,519 - utils.py - hybpiper.assemble - log_or_print - INFO - bbmap.sh             not found in your $PATH!
2024-03-21 16:55:36,519 - utils.py - hybpiper.assemble - log_or_print - INFO - bbmerge.sh           not found in your $PATH!
2024-03-21 16:55:36,519 - utils.py - hybpiper.assemble - log_or_print - INFO - diamond              not found in your $PATH!
2024-03-21 16:55:36,519 - utils.py - hybpiper.assemble - log_or_print - INFO - mafft                found at /usr/bin/mafft
```

...and all gene assemblies failed. Can you find the log file from the run that produced sequences for this sample - I'm assuming you had all the dependencies correctly installed for that one?

Cheers,

Chris

**Comment by bingli8899** [comment]
Hi Chris 

I am very sorry that I uploaded the wrong file. Here, I attached the correct file to this message. Thanks a lot for your help! 

Bing 
[TGB02_L0002_cleaned_hybpiper_assemble_2024-03-23-12_01_10.log](https://github.com/mossmatters/HybPiper/files/14839274/TGB02_L0002_cleaned_hybpiper_assemble_2024-03-23-12_01_10.log)

**Comment by chrisjackson-pellicle** [comment]
Hi Bing,

Ah yep, you can see your log files have lots of the following errors:

```
pebble.common.RemoteTraceback: Traceback (most recent call last):
  File "/home/bli283/anaconda3/lib/python3.7/site-packages/pebble/common.py", line 175, in process_execute
    return Result(SUCCESS, function(*args, **kwargs))
  File "/home/bli283/anaconda3/lib/python3.7/site-packages/hybpiper/assemble.py", line 967, in exonerate
    verbose_logging=verbose_logging)
  File "/home/bli283/anaconda3/lib/python3.7/site-packages/hybpiper/exonerate_hits.py", line 550, in parse_exonerate_and_get_stitched_contig
    verbose_logging=verbose_logging)
  File "/home/bli283/anaconda3/lib/python3.7/site-packages/hybpiper/exonerate_hits.py", line 647, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/bli283/anaconda3/lib/python3.7/site-packages/hybpiper/exonerate_hits.py", line 880, in _parse_searchio_object
    all_window_similarity_triplets[::-1][round(three_prime_slice / 3)][::-1]
TypeError: list indices must be integers or slices, not numpy.float64
```

I see from your log file that you've installed HybPiper into the conda `base` environment, running Python 3.7, but that most of the HybPiper dependencies are found at `/home/bli283/software...`. I'm not sure exactly what's going on there, or what approach you used to install HybPiper, but I suspect the error you're seeing is due to an old version of the Python library `numpy` and/or an old version of Python. I think your best option is to install HybPiper following the recommended process in the instructions [here](https://github.com/mossmatters/HybPiper/wiki/Installation).

Let me know how you go,

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
I'll close this issue, but feel free to re-open it if it's still a problem.

Cheers,

Chris
