### ISSUE TITLE
Hybpiper2 fails at exonerate

### ISSUE THREAD

**Issue by laeserman** [mossmatters/HybPiper#142]
I have just installed Hybpiper2 and I am running through the tutorial data. It seemed to install fine, and check_dependencies finds all of the dependencies. However, the assemble stage fails at the exonerate step. I've pasted the full printout from Hybpiper below. Any ideas on what went wrong? Could I have installed a dependency incorrectly?

`[INFO]:    HybPiper was called with these arguments:
           /home/leserman/miniconda3/envs/hybpiper2/bin/hybpiper assemble -t_dna
           test_targets.fasta -r NZ281_R1_test.fastq NZ281_R2_test.fastq --prefix NZ281
           --bwa

[INFO]:    Number of cpus/threads not specified, using all available (12).
[INFO]:    Checking for external dependencies:

blastx               found at /home/leserman/miniconda3/envs/hybpiper2/bin/blastx
exonerate            found at /home/leserman/miniconda3/envs/hybpiper2/bin/exonerate
parallel             found at /home/leserman/miniconda3/envs/hybpiper2/bin/parallel
makeblastdb          found at /home/leserman/miniconda3/envs/hybpiper2/bin/makeblastdb
spades.py            found at /home/leserman/miniconda3/envs/hybpiper2/bin/spades.py
bwa                  found at /home/leserman/miniconda3/envs/hybpiper2/bin/bwa
samtools             found at /home/leserman/miniconda3/envs/hybpiper2/bin/samtools
bbmap.sh             found at /home/leserman/miniconda3/envs/hybpiper2/bin/bbmap.sh
bbmerge.sh           found at /home/leserman/miniconda3/envs/hybpiper2/bin/bbmerge.sh
diamond              found at /home/leserman/miniconda3/envs/hybpiper2/bin/diamond

[INFO]:    Everything looks good!
[INFO]:    Checking target file FASTA header formatting...
[INFO]:    The target file FASTA header formatting looks good!
[INFO]:    The target file contains at least one sequence for 13 unique genes.
[WARNING]: There are 1 sequences in your target file that contain unexpected stop codons
           when translated in the first forwards frame. If your target file contains only
           protein-coding sequences, please check these sequences. Sequence names can be
           found in the sample log file (if running "hybpiper assemble") or printed below
           (if running "hybpiper check_targetfile").

[WARNING]: There are 1 sequences in your target file that are not multiples of three. If
           your target file contains only protein-coding sequences, please check these
           sequences. Sequence names can be found in the sample log file (if running
           "hybpiper assemble") or printed below (if running "hybpiper check_targetfile").

[CMD]:     time bwa mem -t 12 test_targets.fasta /mnt/c/Users/leserman/Documents/
           test_dataset/NZ281_R1_test.fastq /mnt/c/Users/leserman/
           Documents/test_dataset/NZ281_R2_test.fastq  | samtools view -h
           -b -S - >  NZ281.bam
[INFO]:    Gathering IDs for mapped reads...
samtools: /home/leserman/miniconda3/envs/hybpiper2/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /home/leserman/miniconda3/envs/hybpiper2/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /home/leserman/miniconda3/envs/hybpiper2/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
[INFO]:    In total, 3842 reads from the paired-end read files will be distributed to gene directories
[NOTE]:    Distributing paired reads to gene directories
           Elapsed Time: 0:00:00|############################################################################################################################################################################################|Time:  0:00:00
samtools: /home/leserman/miniconda3/envs/hybpiper2/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /home/leserman/miniconda3/envs/hybpiper2/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /home/leserman/miniconda3/envs/hybpiper2/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
[NOTE]:    0 genes had no good matches.
[NOTE]:    Running initial SPAdes assemblies for 13 genes with reads...
[INFO]:    See file "spades_initial_commands.txt" for a list of SPAdes commands
Academic tradition requires you to cite works you base your article on.
If you use programs that use GNU Parallel to process data for an article in a
scientific publication, please cite:

  Tange, O. (2022, September 22). GNU Parallel 20220922 ('Elizabeth').
  Zenodo. https://doi.org/10.5281/zenodo.7105792

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

More about funding GNU Parallel and the citation notice:
https://www.gnu.org/software/parallel/parallel_design.html#citation-notice

To silence this citation notice: run 'parallel --citation' once.

Computers / CPU cores / Max jobs to run
1:local / 12 / 12

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 0s Left: 0 AVG: 0.54s  local:0/13/100%/0.7s
Command exited with non-zero status 3
39.98user 13.81system 0:08.64elapsed 622%CPU (0avgtext+0avgdata 39428maxresident)k
0inputs+0outputs (0major+511683minor)pagefaults 0swaps
[WARNING]: One or more genes had an error with SPAdes assembly. This may be due to low coverage.
[WARNING]: Total number of genes with failed initial SPAdes run: 3. Gene names can be found in the sample log file.
[INFO]:    Finished running initial SPAdes assemblies for all genes with reads!
[NOTE]:    Re-running SPAdes assemblies for 3 genes with unsuccessful initial assemblies...
[WARNING]: In initial assemblies all Kmers failed for 0 genes; these will not be re-run
[CMD]:     parallel -j 12 --eta --timeout 400% :::: redo_spades_commands.txt >
           spades_redo.log
Academic tradition requires you to cite works you base your article on.
If you use programs that use GNU Parallel to process data for an article in a
scientific publication, please cite:

  Tange, O. (2022, September 22). GNU Parallel 20220922 ('Elizabeth').
  Zenodo. https://doi.org/10.5281/zenodo.7105792

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

More about funding GNU Parallel and the citation notice:
https://www.gnu.org/software/parallel/parallel_design.html#citation-notice

To silence this citation notice: run 'parallel --citation' once.

Come on: You have run parallel 10 times. Isn't it about time
you run 'parallel --citation' once to silence the citation notice?

Computers / CPU cores / Max jobs to run
1:local / 12 / 12

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
ETA: 0s Left: 0 AVG: 0.00s  local:0/3/100%/0.3s
[WARNING]: Total number of genes with failed SPAdes re-runs: 0. Gene names can be found in the sample log file.
[INFO]:    Finished re-running SPAdes assemblies for genes with unsuccessful initial assemblies!
[INFO]:    All SPAdes re-runs completed successfully!
[INFO]:    Running exonerate_hits for 13 genes...
For gene gene002 exonerate() raised: 'Seq' object has no attribute 'ungap'
error.traceback is: Traceback (most recent call last):
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/assemble.py", line 920, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 521, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 626, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 705, in _parse_searchio_object
    seq=Seq(''.join(concatenated_hsp_alignment_seqs)).ungap(gap='-'))
AttributeError: 'Seq' object has no attribute 'ungap'

For gene gene293 exonerate() raised: 'Seq' object has no attribute 'ungap'
error.traceback is: Traceback (most recent call last):
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/assemble.py", line 920, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 521, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 626, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 705, in _parse_searchio_object
    seq=Seq(''.join(concatenated_hsp_alignment_seqs)).ungap(gap='-'))
AttributeError: 'Seq' object has no attribute 'ungap'

For gene gene079 exonerate() raised: 'Seq' object has no attribute 'ungap'
error.traceback is: Traceback (most recent call last):
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/assemble.py", line 920, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 521, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 626, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 705, in _parse_searchio_object
    seq=Seq(''.join(concatenated_hsp_alignment_seqs)).ungap(gap='-'))
AttributeError: 'Seq' object has no attribute 'ungap'

For gene gene012 exonerate() raised: 'Seq' object has no attribute 'ungap'
error.traceback is: Traceback (most recent call last):
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/assemble.py", line 920, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 521, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 626, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 705, in _parse_searchio_object
    seq=Seq(''.join(concatenated_hsp_alignment_seqs)).ungap(gap='-'))
AttributeError: 'Seq' object has no attribute 'ungap'

For gene gene461 exonerate() raised: 'Seq' object has no attribute 'ungap'
error.traceback is: Traceback (most recent call last):
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/assemble.py", line 920, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 521, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 626, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 705, in _parse_searchio_object
    seq=Seq(''.join(concatenated_hsp_alignment_seqs)).ungap(gap='-'))
AttributeError: 'Seq' object has no attribute 'ungap'

For gene gene660 exonerate() raised: 'Seq' object has no attribute 'ungap'
error.traceback is: Traceback (most recent call last):
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/assemble.py", line 920, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 521, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 626, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 705, in _parse_searchio_object
    seq=Seq(''.join(concatenated_hsp_alignment_seqs)).ungap(gap='-'))
AttributeError: 'Seq' object has no attribute 'ungap'

For gene gene111 exonerate() raised: 'Seq' object has no attribute 'ungap'
error.traceback is: Traceback (most recent call last):
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/assemble.py", line 920, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 521, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 626, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 705, in _parse_searchio_object
    seq=Seq(''.join(concatenated_hsp_alignment_seqs)).ungap(gap='-'))
AttributeError: 'Seq' object has no attribute 'ungap'

For gene gene026 exonerate() raised: 'Seq' object has no attribute 'ungap'
error.traceback is: Traceback (most recent call last):
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/assemble.py", line 920, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 521, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 626, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 705, in _parse_searchio_object
    seq=Seq(''.join(concatenated_hsp_alignment_seqs)).ungap(gap='-'))
AttributeError: 'Seq' object has no attribute 'ungap'

For gene gene001 exonerate() raised: 'Seq' object has no attribute 'ungap'
error.traceback is: Traceback (most recent call last):
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/assemble.py", line 920, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 521, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 626, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 705, in _parse_searchio_object
    seq=Seq(''.join(concatenated_hsp_alignment_seqs)).ungap(gap='-'))
AttributeError: 'Seq' object has no attribute 'ungap'

For gene gene006 exonerate() raised: 'Seq' object has no attribute 'ungap'
error.traceback is: Traceback (most recent call last):
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/assemble.py", line 920, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 521, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 626, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 705, in _parse_searchio_object
    seq=Seq(''.join(concatenated_hsp_alignment_seqs)).ungap(gap='-'))
AttributeError: 'Seq' object has no attribute 'ungap'

For gene gene030 exonerate() raised: 'Seq' object has no attribute 'ungap'
error.traceback is: Traceback (most recent call last):
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/assemble.py", line 920, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 521, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 626, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 705, in _parse_searchio_object
    seq=Seq(''.join(concatenated_hsp_alignment_seqs)).ungap(gap='-'))
AttributeError: 'Seq' object has no attribute 'ungap'

For gene gene074 exonerate() raised: 'Seq' object has no attribute 'ungap'
error.traceback is: Traceback (most recent call last):
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/assemble.py", line 920, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 521, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 626, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 705, in _parse_searchio_object
    seq=Seq(''.join(concatenated_hsp_alignment_seqs)).ungap(gap='-'))
AttributeError: 'Seq' object has no attribute 'ungap'

For gene gene298 exonerate() raised: 'Seq' object has no attribute 'ungap'
error.traceback is: Traceback (most recent call last):
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/assemble.py", line 920, in exonerate
    exonerate_result = exonerate_hits.parse_exonerate_and_get_stitched_contig(
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 521, in parse_exonerate_and_get_stitched_contig
    exonerate_result = Exonerate(searchio_object=exonerate_hits_from_alignment,
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 626, in __init__
    self.hits_filtered_by_pct_similarity_dict = self._parse_searchio_object()
  File "/home/leserman/miniconda3/envs/hybpiper2/lib/python3.9/site-packages/hybpiper/exonerate_hits.py", line 705, in _parse_searchio_object
    seq=Seq(''.join(concatenated_hsp_alignment_seqs)).ungap(gap='-'))
AttributeError: 'Seq' object has no attribute 'ungap'

[INFO]:    The exonerate_contigs step of the pipeline failed for the following genes:
           gene002
           gene293
           gene079
           gene012
           gene461
           gene660
           gene111
           gene026
           gene001
           gene006
           gene030
           gene074
           gene298

[INFO]:    Generated sequences from 0 genes!
[WARNING]: Potential long paralogs detected for 0 genes!
[WARNING]: Potential paralogs detected via contig depth for 0 genes!

Finished running "hybpiper assemble" for sample NZ281!`

**Comment by chrisjackson-pellicle** [comment]
Hi @laeserman,

It looks like you're running an older version of HybPiper2 - are you able to install version 2.1.6 and try again? This issue is fixed in more recent versions.

Cheers,

Chris

**Comment by laeserman** [comment]
Oh! I’ll try that. I just downloaded it today so I’m not sure how I got an
older version.


--------------------------------------------------
*Lauren A. Eserman, Ph.D.*
*Research Scientist, Genetics *

*Atlanta Botanical Garden*
1345 Piedmont Ave NE
Atlanta, GA 30309

Ph: 404-585-2043 | Cell: 985-860-0450 | ***@***.***

**Comment by chrisjackson-pellicle** [comment]
Did you manage to get the latest version working ok, @laeserman ? I'll close this issue, if so.

**Comment by laeserman** [comment]
Hi Chris,

Yes! I was, thank you for following up. I had an older version of miniconda
installed. I just deleted everything, reinstalled the new versions, and it
all works now. Thanks!

--------------------------------------------------
*Lauren A. Eserman, Ph.D.*
*Research Coordinator, Research Scientist*

*Atlanta Botanical Garden*
1345 Piedmont Ave NE
Atlanta, GA 30309

Ph: 404-585-2043 | Cell: 985-860-0450 | ***@***.***

**Comment by chrisjackson-pellicle** [comment]
Great!
