### ISSUE TITLE
Issue with paralog_retriever

### ISSUE THREAD

**Issue by TiagoVieiraBotany** [mossmatters/HybPiper#143]
Hi,
I am using hybpiper v.2.1.6 and when trying to run 'paralog_retriever' I got the following output:

#########################################################################
[INFO]:    HybPiper version 2.1.6 was called with these arguments:
           paralog_retriever sample_list.txt -t_dna
           /n/holyscratch01/davis_lab/tlvieira/concatenated_genes.fasta

[INFO]:    Recovering paralog sequences...
[INFO]:    Creating directory: paralogs_all
[INFO]:    Creating directory: paralogs_no_chimeras
[INFO]:    Searching for paralogs for 131 samples, 963 genes...
           Elapsed Time: 0:00:00|                                                                                                                                                           |ETA:  --:--:--No chimeric stitched contig summary file found for sample !
Traceback (most recent call last):
  File "/n/home10/tlvieira/miniconda3/envs/hybpiper/bin/hybpiper", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/n/home10/tlvieira/miniconda3/envs/hybpiper/lib/python3.11/site-packages/hybpiper/assemble.py", line 1873, in main
    args.func(args)
  File "/n/home10/tlvieira/miniconda3/envs/hybpiper/lib/python3.11/site-packages/hybpiper/assemble.py", line 1660, in paralog_retriever_main
    paralog_retriever.main(args)
  File "/n/home10/tlvieira/miniconda3/envs/hybpiper/lib/python3.11/site-packages/hybpiper/paralog_retriever.py", line 430, in main
    num_seqs, has_paralogs, seqs_to_write_all, seqs_to_write_no_chimeras = retrieve_gene_paralogs_from_sample(
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home10/tlvieira/miniconda3/envs/hybpiper/lib/python3.11/site-packages/hybpiper/paralog_retriever.py", line 73, in retrieve_gene_paralogs_from_sample
    chimeric_genes_to_skip = get_chimeric_genes_for_sample(sample_directory_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home10/tlvieira/miniconda3/envs/hybpiper/lib/python3.11/site-packages/hybpiper/retrieve_sequences.py", line 49, in get_chimeric_genes_for_sample
    with open(f'{sample_directory_name}/'
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/_genes_derived_from_putative_chimeric_stitched_contig.csv'

###############################################################################################

Any help about what would be going on here? Many thanks!

**Comment by chrisjackson-pellicle** [comment]
Hi @TiagoVieiraBotany ,

That's odd - `paralog_retriever` appears to be parsing an empty string from your `sample_list.txt` file, which it shouldn't do. Are you able to upload your `sample_list.txt` file, so I can have a look?

Cheers,

Chris

**Comment by TiagoVieiraBotany** [comment]
Hi @chrisjackson-pellicle ,

Your comment brought to my attention an issue with my `sample_list.txt` file. It had `/` at the end of each name (however, notice that it ran smoothly for `stats` and `retrieve_sequences`). I removed the `/` and ran again. Now, it outputted the following message:

######################################################################
[INFO]:    HybPiper version 2.1.6 was called with these arguments:
           paralog_retriever /n/holyscratch01/davis_lab/tlvieira/raw-data-target-dec-8/231
           130_A00794_0971_BHV5NWDSX7_SUB14926/fastq/clean_reads_cutted_dedup/sample_list.
           txt -t_dna /n/holyscratch01/davis_lab/tlvieira/concatenated_genes.fasta

[INFO]:    Recovering paralog sequences...
[INFO]:    Creating directory: paralogs_all
[INFO]:    Creating directory: paralogs_no_chimeras
[INFO]:    Searching for paralogs for 131 samples, 963 genes...
           Elapsed Time: 0:00:00|                                                                                                                                                           |ETA:  --:--:--No chimeric stitched contig summary file found for sample P_rhopa_K47_S41!
Traceback (most recent call last):
  File "/n/home10/tlvieira/miniconda3/envs/hybpiper/bin/hybpiper", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/n/home10/tlvieira/miniconda3/envs/hybpiper/lib/python3.11/site-packages/hybpiper/assemble.py", line 1873, in main
    args.func(args)
  File "/n/home10/tlvieira/miniconda3/envs/hybpiper/lib/python3.11/site-packages/hybpiper/assemble.py", line 1660, in paralog_retriever_main
    paralog_retriever.main(args)
  File "/n/home10/tlvieira/miniconda3/envs/hybpiper/lib/python3.11/site-packages/hybpiper/paralog_retriever.py", line 430, in main
    num_seqs, has_paralogs, seqs_to_write_all, seqs_to_write_no_chimeras = retrieve_gene_paralogs_from_sample(
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home10/tlvieira/miniconda3/envs/hybpiper/lib/python3.11/site-packages/hybpiper/paralog_retriever.py", line 73, in retrieve_gene_paralogs_from_sample
    chimeric_genes_to_skip = get_chimeric_genes_for_sample(sample_directory_name)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/home10/tlvieira/miniconda3/envs/hybpiper/lib/python3.11/site-packages/hybpiper/retrieve_sequences.py", line 49, in get_chimeric_genes_for_sample
    with open(f'{sample_directory_name}/'
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'P_rhopa_K47_S41/P_rhopa_K47_S41_genes_derived_from_putative_chimeric_stitched_contig.csv'

##################################################################################

Thanks for your attention. Much appreciated!

Best,
Tiago

**Comment by chrisjackson-pellicle** [comment]
Hi Tiago,

The `hybpiper assemble` step does check for (and does not allow) slashes in the sample names. I'm guessing you ran the samples as smaller batches and then made a combined `sample_list.txt` file for the downstream steps? In a future update I'll add the check for slashes to the other subcommands too. 

As an aside, `hybpiper retrieve_sequences` still works because it constructs paths to the sequence files using Python's `os.path.join`, which strips out extra slashes. Are you sure `hybpiper stats` ran without error, though? For any sample that had a trailing forward slash in your `sample_list.txt` file I would have expected to see an error message that looked like:

```
[WARNING]: No *.bam or *.blastx file found for EG98/. No statistics will be recovered.
           Please check the log file for this sample!
```

Regarding your current issue with your fixed `sample_list.txt` file, can you confirm:

1) You're running the `hybpiper paralog_retriever` command from the directory that contains all your sample directories (e.g. `P_rhopa_K47_S41`). 

2) The sample directory `P_rhopa_K47_S41` does indeed contain the file `P_rhopa_K47_S41_genes_derived_from_putative_chimeric_stitched_contig.csv`.


Cheers,

Chris

**Comment by TiagoVieiraBotany** [comment]
Hi Chris,

You are correct. I had to run `assemble` on at least 3 batches. Regarding your question 1, yes, I ran the `paralog_retriever` within the directory with all sample directories. Now, checking the `P_rhopa_K47_S41`, for some reason it doesn't have all folder for the target genes, only a few files (see below).

################################################################
(base) [tlvieira@holylogin04 P_rhopa_K47_S41]$ ls
concatenated_genes.fasta      concatenated_genes.fasta.ann  concatenated_genes.fasta.pac  P_rhopa_K47_S41.bam					     P_rhopa_K47_S41_unpaired.bam
concatenated_genes.fasta.amb  concatenated_genes.fasta.bwt  concatenated_genes.fasta.sa   P_rhopa_K47_S41_hybpiper_assemble_2024-03-16-15_39_06.log
##########################################################################

I will run assemble again, everything by once this time, follow with the pipeline to see how it goes until the `paralog_retriever`, and then come back here to update if that worked.

Thanks again,
Tiago

**Comment by chrisjackson-pellicle** [comment]
Hi Tiago,

No worries!

In the meantime, can you send me the `P_rhopa_K47_S41_hybpiper_assemble_2024-03-16-15_39_06.log` file from the `P_rhopa_K47_S41` directory? It's possible that this sample had no reads mapped, or no SPAdes contigs produced, or no coding sequences extracted from SPAdes contigs using Exonerate. 

If one of these scenarios is true, then no  `P_rhopa_K47_S41_genes_derived_from_putative_chimeric_stitched_contig.csv` file will have been written during the `hybpiper assemble` step, and `hybpiper paralog_retriever` will fail with the error message you're seeing. This is a **bug** in the HybPiper pipeline which I will fix in the next update. In the meantime, simply removing this sample from your `sample_list.txt` file should allow `hybpiper paralog_retriever` to run successfully (unless there are other samples that also didn't produce sequences, in which case you could check their log file and remove them from the `sample_list.txt` file as well).

Cheers,

Chris

**Comment by TiagoVieiraBotany** [comment]
Hi Chris,

Yes, now checking the heatmap, for some reason (maybe some issue with that batch division during `assemble`) no targets were recovered for P_rhopa_K47_S41, which is weird since the clean fastq files have ~750MB (for both R1 and R2) and the sample came from "good gDNA". Let's see after a single and smooth `assemble` run, how it goes (I am really curious)... I am attaching here the log file you asked.
[P_rhopa_K47_S41_hybpiper_assemble_2024-03-16-15_39_06.log](https://github.com/mossmatters/HybPiper/files/14877929/P_rhopa_K47_S41_hybpiper_assemble_2024-03-16-15_39_06.log)

Thanks,
Tiago

**Comment by chrisjackson-pellicle** [comment]
Hmm, might be worth re-downloading your read files for that sample again? In your log file I can see errors during the BWA mapping step, e.g.

```
[M::mem_process_seqs] Processed 539444 reads in 31.598 CPU sec, 2.213 real sec
[W::bseq_read] the 2nd file has fewer sequences.
[W::bseq_read] the 2nd file has fewer sequences.
[gzclose] buffer error
```
