### ISSUE TITLE
HybPiper 2.2.0 Retrieve Sequences and Paralog Retriever failing to run on MacOS

### ISSUE THREAD

**Issue by plitof1** [mossmatters/HybPiper#155]
I am reporting these issues together as I am guessing they are related.   I have run this on both Intel Mac and M3 Mac. 

On HybPiper 2.1.8 both functions run without error.  On HybPiper 2.2.0 I am getting the following:

### Retrieve Sequences
**Command:** hybpiper retrieve_sequences -t_dna CH/DCB/data/loci3.fasta dna --sample_names CH/DCB/data/namelist.txt --fasta_dir CH/DCB/Loci3/01_dna_seqs > CH/DCB/Loci3/retriever_sequence_dna.log

**Result:** 
Traceback (most recent call last):
  File "/opt/miniconda3/envs/hybpiper/bin/hybpiper", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/miniconda3/envs/hybpiper/lib/python3.12/site-packages/hybpiper/hybpiper_main.py", line 322, in main
    args.func(args)
  File "/opt/miniconda3/envs/hybpiper/lib/python3.12/site-packages/hybpiper/hybpiper_main.py", line 154, in retrieve_sequences_main
    retrieve_sequences.main(args)
  File "/opt/miniconda3/envs/hybpiper/lib/python3.12/site-packages/hybpiper/retrieve_sequences.py", line 501, in main
    recover_sequences_from_all_samples(seq_dir,
  File "/opt/miniconda3/envs/hybpiper/lib/python3.12/site-packages/hybpiper/retrieve_sequences.py", line 203, in recover_sequences_from_all_samples
    with open(f'{sampledir}/{sample}/{sample}_chimera_check_performed.txt', 'r') as chimera_check_handle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './S160.fastq/S160.fastq_chimera_check_performed.txt'

### Paralog Retriever
**Command:** hybpiper paralog_retriever CH/DCB/data/namelist.txt -t_dna CH/DCB/data/loci3.fasta --fasta_dir_all CH/DCB/Loci3/paralogs_all --fasta_dir_no_chimeras CH/DCB/Loci3/paralogs_no_chimeras --paralog_report_filename CH/DCB/Loci3/paralog_report --paralogs_above_threshold_report_filename CH/DCB/Loci3/paralogs_above_threshold_report --no_heatmap > CH/DCB/Loci3/paralog_retriever.log

**Result:**
Traceback (most recent call last):
  File "/opt/miniconda3/envs/hybpiper/bin/hybpiper", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/miniconda3/envs/hybpiper/lib/python3.12/site-packages/hybpiper/hybpiper_main.py", line 322, in main
    args.func(args)
  File "/opt/miniconda3/envs/hybpiper/lib/python3.12/site-packages/hybpiper/hybpiper_main.py", line 165, in paralog_retriever_main
    paralog_retriever.main(args)
  File "/opt/miniconda3/envs/hybpiper/lib/python3.12/site-packages/hybpiper/paralog_retriever.py", line 419, in main
    with (open(f'{sample}/{sample}_chimera_check_performed.txt', 'r') as chimera_check_handle):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'S160.fastq/S160.fastq_chimera_check_performed.txt'

**Comment by chrisjackson-pellicle** [comment]
Hi @plitof1,

Are you running the commands using HybPiper version 2.2.0 on samples that you assembled with version 2.1.8? HybPiper 2.2.0 writes a new file to each sample directory (`<sample_name>_chimera_check_performed.txt` - see the last dotpoint for v2.2.0 [here](https://github.com/mossmatters/HybPiper/blob/master/change_log.md#changelog)), and this will be missing for samples processed with earlier versions.

I'll fix this so an informative error is produced in the next version. In the meantime, you could create a text file named `<sample_name>_chimera_check_performed.txt` containing the text `True` in your sample directories, and the commands should work as expected. Apologies for the hassle with this.

Cheers,

Chris

**Comment by plitof1** [comment]
Thank you Chris.  I was using v2.2.0 to perform all of the processing, including the assemble.  I had started to read the release notes for 2.2.0.   After adding "--chimeric_stitched_contig_check" the assemble step and all is fine now.

**Comment by chrisjackson-pellicle** [comment]
A more informative error message is produced in this scenario with HybPiper version 2.3.0.
