### ISSUE TITLE
intronerate error

### ISSUE THREAD

**Issue by andycrowl** [mossmatters/HybPiper#48]
Hi Matt --

Getting the following error with intronerate:

`Traceback (most recent call last):
  File "/HybPiper/intronerate.py", line 309, in <module>
    if __name__ == "__main__":main()
  File "/HybPiper/intronerate.py", line 288, in main
    kept_hits = filter_gff(hits,merge=args.merge)
  File "/HybPiper/intronerate.py", line 118, in filter_gff
    kept_indicies = range_connectivity(range_list)
  File "/HybPiper/exonerate_hits.py", line 324, in range_connectivity
    max_length = max(ends) - min(starts)
ValueError: max() arg is an empty sequence
`

This is happening despite the main script successfully assembling exonic regions for this sample. 

Any thoughts??  
Andy

**Comment by mossmatters** [comment]
Andy,

Are you using the master version or the development version? We've attempted a fix for this in the development version: https://github.com/mossmatters/HybPiper/commit/6d8302013a259618e507b140d289d42d3fdc79f4

If you do `git checkout develop` in the HybPiper repo directory it will switch you over. Let me know if it still doesn't work!

~Matt

**Comment by andycrowl** [comment]
Thanks for the quick reply, Matt!  

Hmm, I seem to still be getting the same error..

**Comment by sly1983** [comment]
Hi,
thanks, for me this fixed the problem!
All the best,
Phil
