### ISSUE TITLE
hybpiper_stats.py can't locate .bam file issue

### ISSUE THREAD

**Issue by mdgn15** [mossmatters/HybPiper#64]
Hello again,

I am trying to run hybpiper_stats.py but I am getting the following error.

```
No .bam or .blastx file found for /storage/brno6/home/mdgn15/helio2_exon/idahoa/idahoa_tair
Traceback (most recent call last):
  File "software/HybPiper/hybpiper_stats.py", line 153, in <module>
    if __name__ == "__main__":main()
  File "software/HybPiper/hybpiper_stats.py", line 138, in main
    stats_dict[name] += seq_length_dict[name]
KeyError: '/storage/brno6/home/mdgn15/helio2_exon/idahoa/idahoa_tair'
```

The folder names are correct, a .bam file for .../idahoa/idahoa_tair.bam is present and the namelist.txt file I used is the same one with get_seq_lenghts.py (which worked without any errors). I am running it with python 2.7.6. Do you have any suggestions what might be the problem?

Thanks again!

**Comment by mossmatters** [comment]
`hybpiper_stats.py` uses `namelist.txt` to find HybPiper output directories matching those names in the current directory. 

Do you have full paths in the `namelist.txt`? If you modify them to just be the sample names like "idahoa_tair" it should be the short-term fix.

There is a long-term fix for this in `get_seq_lengths.py` that should be added to `hybpiper_stats.py` in the next version.

**Comment by mdgn15** [comment]
Yes, the full paths are in the namelist.txt. I have the result files in separate directories so I needed to include the full paths. When I remove that species from the namelist.txt, I don't get any errors but stats.txt file returns empty with only headers present. 

The problem is when I go into idahoa_tair directory where the results are and run it there with only 'idahoa_tair' in the namelist.txt this time I get a one line "No .bam or .blastx file found for idahoa_tair". This result is the same for every other individual species folder. So that didn't work as well.

**Comment by mossmatters** [comment]
You should be one directory above the HybPiper output directories to run `get_seq_lengths.py` and `hybpiper_stats.py`.

I typically have my directories set up like:

```
reads
    |
    |-- prefix1.R1.fq
    |-- prefix1.R2.fq
    |-- prefix2.R1.fq
    |-- prefix2.R2.fq
    |-- prefix3.R1.fq
    |-- prefix3.R2.fq
    |-- prefix4.R1.fq
    |-- prefix4.R2.fq
hybpiper_output
    |
    |-- prefix1
    |-- prefix2
    |-- prefix3
    |-- prefix4
``` 

In this case the `.bam` file (and all the gene directories) for `prefix1` would be in `hybpiper_output/prefix1`. So you would run the scripts from the `hybpiper_output` directory with a `namelist.txt` that looks like:

```
prefix1
prefix2
prefix3
prefix4
```

In addition, the names in the first column of `get_seq_lengths.py` should match the `namelist.txt`. So if you changed `namelist.txt` you may need to edit that first column to match.

Let me know if none of that helps and I will look into the fix for `hybpiper_stats.txt` to accommodate full paths.

**Comment by mdgn15** [comment]
Yes, when I tried one directory above, the script worked without any problems. 

Interesting think is I ran `get_seq_lengths.py ` two directories above the separate paths  (`~/main/species1(reads)/prefix1`). So I ran it from `/main/` and not `/species1/ ` before and it worked for  `get_seq_lengths.py ` with each path specified like above and output to  `/main/`. 

Anyway, my last question would be, if I just concatenate all individual stat results in one file, I wouldn't miss any information right? Because in this case I will have to do it like this. So my summarized observation is that paths work in namelist.txt for `get_seq_lengths.py ` but not in `hybpiper_stats.py`. 

Thanks for the assistance!
