### ISSUE TITLE
Hybpiper stats fails when namelist contains failed sample

### ISSUE THREAD

**Issue by mossmatters** [mossmatters/HybPiper#81]
This is a minor issue but `hybpiper stats` fails when there is a `.bam` file associated with a `prefix` in the `namelist.txt` but the `.bam` file is misformatted or empty:

```
Failed to read header for "ARGANseq159/ARGANseq159.bam"
Traceback (most recent call last):
  File "/opt/apps/anaconda/anaconda3/envs/hybpiper/bin/hybpiper", line 10, in <module>
    sys.exit(main())
  File "/opt/apps/anaconda/anaconda3/envs/hybpiper/lib/python3.9/site-packages/hybpiper/assemble.py", line 1689, in main
    args.func(args)
  File "/opt/apps/anaconda/anaconda3/envs/hybpiper/lib/python3.9/site-packages/hybpiper/assemble.py", line 1502, in hybpiper_stats_main
    hybpiper_stats.main(args)
  File "/opt/apps/anaconda/anaconda3/envs/hybpiper/lib/python3.9/site-packages/hybpiper/hybpiper_stats.py", line 351, in main
    stats_dict[name] += enrich_efficiency_bwa(bamfile)
  File "/opt/apps/anaconda/anaconda3/envs/hybpiper/lib/python3.9/site-packages/hybpiper/hybpiper_stats.py", line 199, in enrich_efficiency_bwa
    pctMapped = 100 * mappedReads / numReads
UnboundLocalError: local variable 'mappedReads' referenced before assignment
```

This resulted because one of the samples had badly formed fastq headers so BWA created the `.bam` but it is empty:

```
[...snip...]
Command terminated by signal 11
1.82user 0.41system 0:04.37elapsed 51%CPU (0avgtext+0avgdata 534060maxresident)k
241368inputs+0outputs (0major+190684minor)pagefaults 0swaps
[W::sam_hdr_create] Ignored @SQ SN:QSKP-5296_ : bad or missing LN tag
[E::sam_hrecs_update_hashes] Header includes @SQ line "QSKP-5296_" with no LN: tag
samtools view: failed to add PG line to the header

2022-06-13 16:42:20,706 - assemble.py - hybpiper.assemble - assemble - ERROR - [ERROR]:   Something went wrong with the BWA step, exiting. Check the hybpiper_assemble.log file for sample ARGANseq159!
``` 

We should probably: 
- add a check for whether we can get `mappedReads` for that sample before attempting to calculate `pctMapped` 
- delete the `.bam` file if we're exiting with a "Something went wrong with BWA" error

**Comment by chrisjackson-pellicle** [comment]
@mossmatters - change added and pushed to git repo, and OSX and Linux conda packages rebuilt and pushed. Can you test and confirm it's working as expected?
